/**
 * Single source of truth for woreda / sub-city identity.
 * When duplicating this project for another woreda, change only this file:
 *   - woredaNumber: optional, e.g. leave empty for generic "Woreda"
 *   - subcity.am / subcity.en / subcity.om: your sub-city name in each language
 *   - emailDomain: e.g. 'woreda.gov.et'
 *
 * Leave woredaNumber and subcity empty for generic labels (no specific number or name).
 */
export const siteConfig = {
  woredaNumber: '',
  subcity: {
    am: '',
    en: '',
    om: '',
  },
  emailDomain: 'woreda.gov.et',
  /** Public portal URL for SMS tracking links (update when deployed) */
  publicSiteUrl: 'https://woreda-portal.vercel.app',
  storageKeyPrefix: 'woreda_portal',
  // Optional woreda-specific stats (leave null to hide from home page)
  stats: {
    population: null,
    blocks: null,
  },
}

const BASE = {
  woreda: { am: 'ወረዳ', en: 'Woreda', om: 'Aanaa' },
  subcity: { am: 'ክፍለ ከተማ', en: 'Sub-City', om: 'Magaalaa Xiqqoo' },
  administration: { am: 'አስተዳደር', en: 'Administration', om: 'Bulchiinsa' },
  digitalService: { am: 'ዲጂታል አገልግሎት', en: 'Digital Service', om: 'Tajaajila Dijitaalaa' },
  digitalPortal: { am: 'ዲጂታል አገልግሎት ፖርታል', en: 'Digital Service Portal', om: 'Paanelii Tajaajila Dijitaalaa' },
}

export function getWoredaLabel(lang = 'am') {
  const base = BASE.woreda[lang] || BASE.woreda.en
  const num = siteConfig.woredaNumber?.trim()
  return num ? `${base} ${num}` : base
}

export function getSubcityLabel(lang = 'am') {
  const specific = siteConfig.subcity[lang]?.trim()
  if (specific) return specific
  return BASE.subcity[lang] || BASE.subcity.en
}

export function getWoredaAdministration(lang = 'am') {
  const admin = BASE.administration[lang] || BASE.administration.en
  return `${getWoredaLabel(lang)} ${admin}`
}

export function getSubcityWoredaLabel(lang = 'am') {
  return `${getSubcityLabel(lang)} ${getWoredaLabel(lang)}`
}

export function getWelcomeSubtitle(lang = 'am') {
  const admin = getWoredaAdministration(lang)
  if (lang === 'am') return `${admin} ${BASE.digitalPortal.am}`
  if (lang === 'om') return `${getWoredaLabel(lang)} ${getSubcityLabel(lang)} ${BASE.digitalPortal.om}`
  return `${getSubcityWoredaLabel(lang)} ${BASE.digitalPortal.en}`
}

export function getHeroSubtitle(lang = 'am') {
  const admin = getWoredaAdministration(lang)
  if (lang === 'am') {
    return `${admin} አገልግሎቶችን በዲጂታል መንገድ ያግኙ። `
  }
  if (lang === 'om') {
    return `Tajaajila bulchiinsa ${getWoredaLabel(lang)} karaa dijitaalaatiin argadhaa. Saffisaa, gahumsa qabu fi dhaqqabamaa.`
  }
  return `Access ${admin.toLowerCase()} services digitally. Fast, efficient, and accessible.`
}

export function getMissionStatement(lang = 'am') {
  const woreda = getWoredaLabel(lang)
  if (lang === 'am') return `የ${woreda} የዲጂታል ሽግግር ራይ`
  if (lang === 'om') return `Mul'ata Jijjiirama Dijitaalaa ${woreda}`
  return `${woreda} Digital Transformation Vision`
}

export function getDigitalTransformationSpeech(lang = 'am') {
  const mission = getMissionStatement(lang)
  if (lang === 'am') {
    return `${mission} - ሁሉንም ነዋሪዎች ወደ ዘመናዊ የአገልግሎት ስርዓት ለመሸጋገር እየሰራን ነን።`
  }
  if (lang === 'om') {
    return `${mission} - Jiraattoota hunda gara sirna tajaajila ammayyaatti ce'uuf hojjechaa jirra.`
  }
  return `${mission} - We are working to transition all residents to a modern service system.`
}

export function getLeadershipTeamSubtitle(lang = 'am') {
  const woreda = getWoredaLabel(lang)
  if (lang === 'am') return `የ${woreda} አመራሮች እና አመራር ቡድን`
  if (lang === 'om') return `Garee Hoggansa ${woreda}`
  return `${woreda} Leadership Team`
}

export function getCopyrightText(lang = 'am', year = new Date().getFullYear()) {
  const woreda = getWoredaLabel(lang)
  if (lang === 'am') return `© ${year} ${woreda}. ሁሉም መብቶች የተጠበቁ ናቸው።`
  if (lang === 'om') return `© ${year} ${woreda}. Mirgi hundi eegameera.`
  return `© ${year} ${woreda}. All rights reserved.`
}

export function getDigitalPortalName(lang = 'am') {
  if (lang === 'am') return `${getWoredaLabel(lang)} ${BASE.digitalPortal.am}`
  if (lang === 'om') return `${getWoredaLabel(lang)} ${BASE.digitalPortal.om}`
  return `${getWoredaLabel(lang)} ${BASE.digitalPortal.en}`
}

export function getPdfFooterText(lang = 'am') {
  const portal = getDigitalPortalName(lang)
  if (lang === 'am') return `ይህ ሰነድ በ${portal} በራስ-ሰር ተመንግዷል።`
  return `This document was automatically generated by ${portal}.`
}

export function getPortalEmail(localPart) {
  return `${localPart}@${siteConfig.emailDomain}`
}

export const portalEmailRoles = {
  trade: 'trade',
  civil: 'civil',
  labor: 'labor',
  ceo: 'ceo',
  chiefExecutive: 'chief.executive',
  councilSpeaker: 'council.speaker',
  admin: 'admin',
}

const roleKeyToEmailLocal = {
  trade_head: portalEmailRoles.trade,
  civil_head: portalEmailRoles.civil,
  labor_head: portalEmailRoles.labor,
  ceo_office_head: portalEmailRoles.ceo,
  ceo: portalEmailRoles.chiefExecutive,
  council_speaker: portalEmailRoles.councilSpeaker,
  admin: portalEmailRoles.admin,
}

/** Default portal login email for a role (users may override if their account differs). */
export function getPortalEmailForRole(roleKey) {
  const local = roleKeyToEmailLocal[roleKey]
  return local ? getPortalEmail(local) : ''
}
